name: acanthis
description: Acanthis is an easy-to-use validation library for Dart and Flutter.
version: 0.0.1
homepage: https://acanthis.serinus.app
repository: https://github.com/francescovallone/acanthis


environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  email_validator: ^2.1.17
  
  # path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^3.0.0
  test: ^1.24.0
