name: acanthis
description: Acanthis is an easy-to-use validation library for Dart and Flutter.
version: 0.1.3
homepage: https://acanthis.serinus.app
documentation: https://acanthis.serinus.app/introduction.html
repository: https://github.com/francescovallone/acanthis

topics:
  - validation
  - dart
  - validation-form
  - validators


environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  email_validator: ^2.1.17
  
  # path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^3.0.0
  test: ^1.24.0
